<?php
/**
 * HotelAvailabilityRQTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PlugAndTravel
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PlugAndTravel.BookingAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PlugAndTravel;

/**
 * HotelAvailabilityRQTest Class Doc Comment
 *
 * @category    Class */
// * @description HotelAvailabilityRQ
/**
 * @package     PlugAndTravel
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HotelAvailabilityRQTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "HotelAvailabilityRQ"
     */
    public function testHotelAvailabilityRQ()
    {

    }

    /**
     * Test attribute "customer_ip_address"
     */
    public function testPropertyCustomerIpAddress()
    {

    }

    /**
     * Test attribute "customer_user_agent"
     */
    public function testPropertyCustomerUserAgent()
    {

    }

    /**
     * Test attribute "destination_code"
     */
    public function testPropertyDestinationCode()
    {

    }

    /**
     * Test attribute "check_in"
     */
    public function testPropertyCheckIn()
    {

    }

    /**
     * Test attribute "check_out"
     */
    public function testPropertyCheckOut()
    {

    }

    /**
     * Test attribute "passenger_country"
     */
    public function testPropertyPassengerCountry()
    {

    }

    /**
     * Test attribute "occupancies"
     */
    public function testPropertyOccupancies()
    {

    }

    /**
     * Test attribute "provider"
     */
    public function testPropertyProvider()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "hotel_codes"
     */
    public function testPropertyHotelCodes()
    {

    }

}
