<?php
/**
 * RoomRSTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PlugAndTravel
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PlugAndTravel.BookingAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PlugAndTravel;

/**
 * RoomRSTest Class Doc Comment
 *
 * @category    Class */
// * @description RoomRS
/**
 * @package     PlugAndTravel
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RoomRSTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RoomRS"
     */
    public function testRoomRS()
    {

    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "bed_types"
     */
    public function testPropertyBedTypes()
    {

    }

    /**
     * Test attribute "hotel_code"
     */
    public function testPropertyHotelCode()
    {

    }

    /**
     * Test attribute "provider_hotel_code"
     */
    public function testPropertyProviderHotelCode()
    {

    }

    /**
     * Test attribute "provider"
     */
    public function testPropertyProvider()
    {

    }

    /**
     * Test attribute "tokens"
     */
    public function testPropertyTokens()
    {

    }

    /**
     * Test attribute "occupancy"
     */
    public function testPropertyOccupancy()
    {

    }

    /**
     * Test attribute "price_changed"
     */
    public function testPropertyPriceChanged()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "is_non_refundable"
     */
    public function testPropertyIsNonRefundable()
    {

    }

    /**
     * Test attribute "cancellation_policies"
     */
    public function testPropertyCancellationPolicies()
    {

    }

    /**
     * Test attribute "room_supplements"
     */
    public function testPropertyRoomSupplements()
    {

    }

    /**
     * Test attribute "person_supplements"
     */
    public function testPropertyPersonSupplements()
    {

    }

    /**
     * Test attribute "room_taxes"
     */
    public function testPropertyRoomTaxes()
    {

    }

    /**
     * Test attribute "essential_information"
     */
    public function testPropertyEssentialInformation()
    {

    }

    /**
     * Test attribute "meal"
     */
    public function testPropertyMeal()
    {

    }

}
